version: '3.8'
services:
  frontend:
    build:
      context: .
    image: sakane-frontend:latest
    container_name: sakane-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://admin.sakane.ma
    command: ["sh", "-c", "bash /app/cleanup.sh && npm start"]
